// Generated by build.mjs. Edit the source modules and rebuild.
(() => {
'use strict';
// ---- reference/figure2-data.js ----
// Transcribed from ../example_output.txt, block 9. Values in that output are rounded.
// The underlying Python simulation remains the reference implementation.
const SWEEP = Object.freeze([
  { interval: 5,     alarmsPerYear: 35.00, detection: { NICU: .388, LNU: .697, SCU: .910 }, backgroundLnu: .155, ratioAtPoint1: 35664, ratioAt1: 3566, yearsAtPoint1: 1019, yearsAt1: 102 },
  { interval: 10,    alarmsPerYear: 17.50, detection: { NICU: .247, LNU: .545, SCU: .832 }, backgroundLnu: .068, ratioAtPoint1: 23695, ratioAt1: 2370, yearsAtPoint1: 1354, yearsAt1: 135 },
  { interval: 20,    alarmsPerYear: 8.75,  detection: { NICU: .152, LNU: .399, SCU: .716 }, backgroundLnu: .027, ratioAtPoint1: 16375, ratioAt1: 1637, yearsAtPoint1: 1871, yearsAt1: 187 },
  { interval: 50,    alarmsPerYear: 3.50,  detection: { NICU: .077, LNU: .235, SCU: .529 }, backgroundLnu: .007, ratioAtPoint1: 10857, ratioAt1: 1086, yearsAtPoint1: 3102, yearsAt1: 310 },
  { interval: 100,   alarmsPerYear: 1.75,  detection: { NICU: .045, LNU: .147, SCU: .390 }, backgroundLnu: .002, ratioAtPoint1: 8362,  ratioAt1: 836,  yearsAtPoint1: 4778, yearsAt1: 478 },
  { interval: 200,   alarmsPerYear: .88,   detection: { NICU: .025, LNU: .084, SCU: .270 }, backgroundLnu: .000, ratioAtPoint1: 6849,  ratioAt1: 685,  yearsAtPoint1: 7828, yearsAt1: 783 },
  { interval: 500,   alarmsPerYear: .35,   detection: { NICU: .012, LNU: .036, SCU: .153 }, backgroundLnu: .000, ratioAtPoint1: 5612,  ratioAt1: 561,  yearsAtPoint1: 16035, yearsAt1: 1603 },
  { interval: 1000,  alarmsPerYear: .17,   detection: { NICU: .006, LNU: .019, SCU: .098 }, backgroundLnu: .000, ratioAtPoint1: 4858,  ratioAt1: 486,  yearsAtPoint1: 27757, yearsAt1: 2776 },
  { interval: 2000,  alarmsPerYear: .09,   detection: { NICU: .003, LNU: .009, SCU: .058 }, backgroundLnu: .000, ratioAtPoint1: 4497,  ratioAt1: 450,  yearsAtPoint1: 51390, yearsAt1: 5139 },
  { interval: 5000,  alarmsPerYear: .04,   detection: { NICU: .002, LNU: .003, SCU: .027 }, backgroundLnu: .000, ratioAtPoint1: 4003,  ratioAt1: 400,  yearsAtPoint1: 114385, yearsAt1: 11438 },
  { interval: 10000, alarmsPerYear: .02,   detection: { NICU: .001, LNU: .002, SCU: .014 }, backgroundLnu: .000, ratioAtPoint1: 4014,  ratioAt1: 401,  yearsAtPoint1: 229385, yearsAt1: 22938 }
]);

// ---- presets.js ----
const PAPER_DEFAULT = Object.freeze({
  thresholdIndex: 1,              // E10, one of the paper's two tabulated settings
  prevalencePer10k: 1,            // neonatal reference scenario
  unitType: 'LNU',                 // Figure 2 uses local-unit detection on x-axis
  expectedExtraDeaths: 4,
  riskAllocation: 'staff-proportional',
  unitCounts: Object.freeze({ NICU: 45, LNU: 85, SCU: 45 }),
  annualBackgroundDeaths: Object.freeze({ NICU: 20, LNU: 4, SCU: 1 }),
  caseMixCV: .25
});

const UNIT_NAMES = Object.freeze({ NICU: 'Intensive care unit', LNU: 'Local unit', SCU: 'Special care unit' });

// ---- model.js ----
const PREVALENCE_MIN = .1;
const PREVALENCE_MAX = 30;

function sliderToPrevalence(position) {
  const logMin = Math.log10(PREVALENCE_MIN);
  const logMax = Math.log10(PREVALENCE_MAX);
  return 10 ** (logMin + (Number(position) / 100) * (logMax - logMin));
}

function prevalenceToSlider(prevalence) {
  return Math.round(100 * (Math.log10(prevalence) - Math.log10(PREVALENCE_MIN)) /
    (Math.log10(PREVALENCE_MAX) - Math.log10(PREVALENCE_MIN)));
}

function calculatePoint(row, prevalencePer10k, unitType) {
  if (!(prevalencePer10k > 0) || !row.detection[unitType]) throw new RangeError('Invalid model state');
  // Figure 2 uses false CUSUM crossings on fixed null paths as the numerator.
  // Detected offender-years scale linearly with prevalence. The .1 reference
  // has more printed digits than the 1 reference, so it is the arithmetic anchor.
  const falsePerTrue = row.ratioAtPoint1 * .1 / prevalencePer10k;
  const falseCrossingsPerYear = 175 / row.interval;
  const trueDetectionsPerYear = falseCrossingsPerYear / falsePerTrue;
  return {
    interval: row.interval,
    detectionProbability: row.detection[unitType],
    falsePerTrue,
    falseCrossingsPerYear,
    trueDetectionsPerYear,
    yearsPerDetection: 1 / trueDetectionsPerYear,
    byUnit: row.detection
  };
}

function calculate(state) {
  if (!Number.isInteger(state.thresholdIndex) || state.thresholdIndex < 0 || state.thresholdIndex >= SWEEP.length) {
    throw new RangeError('Invalid threshold index');
  }
  const curve = SWEEP.map(row => calculatePoint(row, state.prevalencePer10k, state.unitType));
  return {
    curve,
    selected: curve[state.thresholdIndex],
    neonatalCurve: SWEEP.map(row => calculatePoint(row, 1, state.unitType)),
    nationalCurve: SWEEP.map(row => calculatePoint(row, .1, state.unitType))
  };
}

// ---- charts.js ----
const NS = 'http://www.w3.org/2000/svg';
const LOG_X_SPAN = Math.log10(2000); // 0.05% to 100%

function node(name, attrs = {}, text = '') {
  const element = document.createElementNS(NS, name);
  for (const [key, value] of Object.entries(attrs)) element.setAttribute(key, value);
  if (text) element.textContent = text;
  return element;
}

function label(value) {
  return value >= 1000 ? `${value / 1000}k` : String(value);
}

function scales(plot) {
  return {
    x: probability => plot.left + (Math.log10(probability) + LOG_X_SPAN) / LOG_X_SPAN * (plot.right - plot.left),
    y: ratio => plot.bottom - (Math.log10(ratio) - 1) / 4 * (plot.bottom - plot.top)
  };
}

function drawTradeoff(svg, result, state, onPointSelected) {
  const title = svg.querySelector('title');
  const desc = svg.querySelector('desc');
  const compact = window.matchMedia('(max-width:760px)').matches;
  svg.setAttribute('viewBox', compact ? '0 0 420 350' : '0 0 760 440');
  const plot = compact ? { left: 49, right: 405, top: 21, bottom: 286 } : { left: 82, right: 730, top: 25, bottom: 358 };
  // The paper uses a log sensitivity axis so the low-detection tail remains legible.
  const { x, y } = scales(plot);
  const contents = [title, desc];
  const grid = node('g', { class: 'chart-grid' });

  for (const tick of [10, 100, 1000, 10000, 100000]) {
    const yy = y(tick);
    grid.append(node('line', { x1: plot.left, x2: plot.right, y1: yy, y2: yy }));
    grid.append(node('text', { x: plot.left - 13, y: yy + 4, 'text-anchor': 'end' }, label(tick)));
  }
  for (const [tick, tickLabel] of [[.001, '0.1%'], [.01, '1%'], [.1, '10%'], [1, '100%']]) {
    const xx = x(tick);
    grid.append(node('line', { x1: xx, x2: xx, y1: plot.top, y2: plot.bottom, class: 'vertical' }));
    grid.append(node('text', { x: xx, y: plot.bottom + 26, 'text-anchor': 'middle' }, tickLabel));
  }
  contents.push(grid);

  const pathFor = curve => curve.map((point, index) =>
    `${index ? 'L' : 'M'} ${x(point.detectionProbability).toFixed(2)} ${y(point.falsePerTrue).toFixed(2)}`).join(' ');

  if (state.prevalencePer10k !== .1) contents.push(node('path', { d: pathFor(result.nationalCurve), class: 'reference-curve national' }));
  if (state.prevalencePer10k !== 1) contents.push(node('path', { d: pathFor(result.neonatalCurve), class: 'reference-curve neonatal' }));
  contents.push(node('path', { d: pathFor(result.curve), class: 'active-curve' }));

  const dots = node('g', { class: 'chart-dots' });
  result.curve.forEach((point, index) => {
    const selected = index === state.thresholdIndex;
    const group = node('g', { class: selected ? 'chart-dot selected' : 'chart-dot', tabindex: '0', role: 'button',
      'aria-label': `One false crossing per ${point.interval} unit-years; detection ${Math.round(point.detectionProbability * 1000) / 10} percent; ${Math.round(point.falsePerTrue)} false crossings per detection` });
    group.append(node('circle', { cx: x(point.detectionProbability), cy: y(point.falsePerTrue), r: selected ? 9 : 5 }));
    group.append(node('circle', { cx: x(point.detectionProbability), cy: y(point.falsePerTrue), r: 17, class: 'hit-area' }));
    group.append(node('title', {}, `1 in ${point.interval} unit-years`));
    group.addEventListener('click', () => onPointSelected(index));
    group.addEventListener('keydown', event => {
      if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); onPointSelected(index); }
    });
    dots.append(group);
  });
  contents.push(dots);

  const selected = result.selected;
  const xx = x(selected.detectionProbability);
  const yy = y(selected.falsePerTrue);
  const annotation = node('g', { class: 'chart-annotation' });
  annotation.append(node('line', { x1: xx, x2: xx, y1: yy + 12, y2: plot.bottom, class: 'guide' }));
  annotation.append(node('text', { x: Math.min(xx + 13, compact ? 346 : 630), y: Math.max(yy - 16, 20) }, `1 in ${selected.interval}`));
  contents.push(annotation);

  svg.replaceChildren(...contents);
  desc.textContent = `Both axes are logarithmic. Selected target: one false crossing in ${selected.interval} unit-years. The selected unit type has a ${(selected.detectionProbability * 100).toFixed(1)} percent chance of an alarm during an offender-year. The model gives ${Math.round(selected.falsePerTrue)} false-alarm crossings per detected offender-year across 175 units.`;
}

function drawUnitChart(svg, point, selectedType) {
  const title = svg.querySelector('title');
  const desc = svg.querySelector('desc');
  const contents = [title, desc];
  const chart = node('g', { class: 'unit-bars' });
  const left = 137;
  const width = 315;
  for (const tick of [0, .25, .5, .75, 1]) {
    const xx = left + tick * width;
    chart.append(node('line', { x1: xx, x2: xx, y1: 25, y2: 197, class: 'bar-grid' }));
    chart.append(node('text', { x: xx, y: 220, 'text-anchor': 'middle', class: 'bar-axis-label' }, `${tick * 100}%`));
  }
  const rows = [['NICU', 'Intensive care'], ['LNU', 'Local'], ['SCU', 'Special care']];
  rows.forEach(([key, name], index) => {
    const yy = 44 + index * 62;
    const value = point.byUnit[key];
    chart.append(node('text', { x: 0, y: yy + 21, class: key === selectedType ? 'bar-name selected-name' : 'bar-name' }, name));
    chart.append(node('rect', { x: left, y: yy, width, height: 30, rx: 6, class: 'bar-track' }));
    chart.append(node('rect', { x: left, y: yy, width: Math.max(value * width, 2), height: 30, rx: 6,
      class: key === selectedType ? 'bar-fill selected-bar' : 'bar-fill' }));
    chart.append(node('text', { x: Math.min(left + value * width + 9, 463), y: yy + 21, class: 'bar-value' }, `${(value * 100).toFixed(1)}%`));
  });
  contents.push(chart);
  svg.replaceChildren(...contents);
  desc.textContent = rows.map(([key, name]) => `${name}: ${(point.byUnit[key] * 100).toFixed(1)} percent`).join('; ');
}

// ---- ui.js ----
let state = { ...PAPER_DEFAULT };
const $ = selector => document.querySelector(selector);
const number = new Intl.NumberFormat('en', { maximumFractionDigits: 0 });

function formatPrevalence(value) {
  return new Intl.NumberFormat('en', { maximumSignificantDigits: 2 }).format(value);
}

function render() {
  const result = calculate(state);
  const selected = result.selected;
  $('#threshold-slider').value = String(state.thresholdIndex);
  $('#prevalence-slider').value = String(prevalenceToSlider(state.prevalencePer10k));
  $(`input[name="unit-type"][value="${state.unitType}"]`).checked = true;
  $('#threshold-value').textContent = `1 in ${number.format(selected.interval)} unit-years`;
  $('#prevalence-value').textContent = `${formatPrevalence(state.prevalencePer10k)} per 10,000 unit-years`;
  $('#ratio-value').textContent = `${number.format(Math.round(selected.falsePerTrue))} : 1`;
  $('#detection-value').textContent = `${(selected.detectionProbability * 100).toFixed(1)}%`;
  $('#selected-unit-label').textContent = `${UNIT_NAMES[state.unitType]} with an offender present`;
  $('#wait-value').textContent = `${number.format(Math.round(selected.yearsPerDetection))} years`;

  document.querySelectorAll('[data-threshold]').forEach(button => {
    button.setAttribute('aria-pressed', String(Number(button.dataset.threshold) === state.thresholdIndex));
  });
  document.querySelectorAll('[data-prevalence]').forEach(button => {
    button.setAttribute('aria-pressed', String(Number(button.dataset.prevalence) === state.prevalencePer10k));
  });
  $('.neonatal-legend').hidden = state.prevalencePer10k === 1;
  $('.national-legend').hidden = state.prevalencePer10k === .1;
  drawTradeoff($('#tradeoff-chart'), result, state, thresholdIndex => setState({ thresholdIndex }));
  drawUnitChart($('#unit-chart'), selected, state.unitType);
}

function setState(patch) {
  state = { ...state, ...patch };
  render();
}

$('#threshold-slider').addEventListener('input', event => setState({ thresholdIndex: Number(event.target.value) }));
$('#prevalence-slider').addEventListener('input', event => setState({ prevalencePer10k: sliderToPrevalence(event.target.value) }));
document.querySelectorAll('input[name="unit-type"]').forEach(input => {
  input.addEventListener('change', event => setState({ unitType: event.target.value }));
});
document.querySelectorAll('[data-threshold]').forEach(button => {
  button.addEventListener('click', () => setState({ thresholdIndex: Number(button.dataset.threshold) }));
});
document.querySelectorAll('[data-prevalence]').forEach(button => {
  button.addEventListener('click', () => setState({ prevalencePer10k: Number(button.dataset.prevalence) }));
});
$('#reset-button').addEventListener('click', () => { state = { ...PAPER_DEFAULT }; render(); });

// Keep the source dataset's 11 settings in the slider's accessible range.
$('#threshold-slider').max = String(SWEEP.length - 1);
window.addEventListener('resize', render);
render();

})();
