import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath, pathToFileURL } from 'node:url';
import path from 'node:path';

const sources = [
  'sim/worker-client.js',
  'reference/figure2-data.js',
  'presets.js',
  'model.js',
  'charts.js',
  'derive.js',
  'tabs/common.js',
  'tabs/tab1.js',
  'tabs/tab2.js',
  'tabs/tab3.js',
  'tabs/tab4.js',
  'tabs/tab5.js',
  'ui.js'
];

const workerSources = [
  'sim/random.js',
  'sim/distributions.js',
  'sim/model.js',
  'sim/worker.js'
];

function stripModules(contents, source) {
  const transformed = contents
    .replace(/^import\s+.*\s+from\s+['"][^'"]+['"];\s*$/gm, '')
    .replace(/^export\s+(?=(?:const|function)\b)/gm, '');
  if (/^\s*(?:import|export)\s/m.test(transformed)) throw new Error(`Unsupported module syntax in ${source}`);
  return transformed.trim();
}

export async function makeBundle() {
  const reference = JSON.parse(await readFile(new URL('reference/reference.json', import.meta.url), 'utf8'));
  const referenceSource = `const REFERENCE = ${JSON.stringify(reference)};`;
  const workerChunks = [referenceSource];
  for (const source of workerSources) {
    const contents = await readFile(new URL(source, import.meta.url), 'utf8');
    workerChunks.push(`// ---- ${source} ----\n${stripModules(contents, source)}`);
  }
  const chunks = [
    `// ---- reference/reference.json (inlined for file://) ----\n${referenceSource}\n`,
    `// ---- Blob worker source ----\nconst SIM_WORKER_SOURCE = ${JSON.stringify(`'use strict';\n${workerChunks.join('\n\n')}\n`)};\n`
  ];
  for (const source of sources) {
    const contents = await readFile(new URL(source, import.meta.url), 'utf8');
    chunks.push(`// ---- ${source} ----\n${stripModules(contents, source)}\n`);
  }
  return `// Generated by build.mjs. Edit the source modules and rebuild.\n(() => {\n'use strict';\n${chunks.join('\n')}\n})();\n`;
}

const invokedPath = process.argv[1] && pathToFileURL(path.resolve(process.argv[1])).href;
if (invokedPath === import.meta.url) {
  const bundle = await makeBundle();
  const output = fileURLToPath(new URL('app.js', import.meta.url));
  if (process.argv.includes('--check')) {
    if (await readFile(output, 'utf8') !== bundle) throw new Error('app.js needs rebuilding');
    process.stdout.write('app.js is up to date\n');
  } else {
    await writeFile(output, bundle);
    process.stdout.write('Built app.js\n');
  }
}
